# Generated by Django 4.1.5 on 2023-01-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('ids', models.PositiveIntegerField(default=0)),
                ('assets', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=100)),
            ],
        ),
    ]
