# Generated by Django 4.1.5 on 2023-01-30 09:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='owner',
            field=models.ForeignKey(default=datetime.datetime(2023, 1, 30, 9, 31, 35, 133538, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d5', models.PositiveIntegerField(default=0)),
                ('bank', models.ForeignKey(default=datetime.datetime(2023, 1, 30, 9, 31, 35, 133538, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='game.bankmodel')),
            ],
        ),
    ]
