# Generated by Django 4.1.5 on 2023-01-31 02:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_bankmodel_owner_yearmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearmodel',
            name='d5',
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='b108',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='b111',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='b75',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='b76',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='b77',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='b78',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='c84',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='c85',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='c89',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='d108',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='d111',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='d75',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='d76',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='d77',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='d78',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='e84',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='e85',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='e89',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='owner',
            field=models.ForeignKey(default=datetime.datetime(2023, 1, 31, 2, 45, 41, 850509, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yearmodel',
            name='bank',
            field=models.ForeignKey(default=datetime.datetime(2023, 1, 31, 2, 45, 41, 850509, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='game.bankmodel'),
        ),
    ]
