# Generated by Django 4.1.5 on 2023-01-31 18:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_yearmodel_d5_bankmodel_b108_bankmodel_b111_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='owner',
            field=models.ForeignKey(default=datetime.datetime(2023, 1, 31, 18, 53, 21, 866959, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yearmodel',
            name='bank',
            field=models.ForeignKey(default=datetime.datetime(2023, 1, 31, 18, 53, 21, 866959, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='game.bankmodel'),
        ),
    ]
